version: '3.1'

services:
  mysql_db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: schedule_db
      MYSQL_USER: example
      MYSQL_PASSWORD: secret2